
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client-id # get a client-id from https://console.developers.google.com/
            client-secret: client-secret # get a client-secret from https://console.developers.google.com/



camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks


server:
  port : 8080




